### ISSUE TITLE
v3.1.99 Qt crashes after start

### ISSUE THREAD

**Issue by danpla** [manisandro/gImageReader#108]
```
gImageReader 3.1.99 ()
#0  0x00007f3482c46c53 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f34852622c7 in qt_safe_select(int, fd_set*, fd_set*, fd_set*, timeval const*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007f3485210c52 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00007f348521244a in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007f34851c8652 in QProcess::waitForFinished(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00000000004529ee in MainWindow::signalHandler(int) ()
#6  <signal handler called>
#7  0x00007f3485e5633a in ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const () from /usr/lib/libtesseract.so.3
#8  0x00007f3485de7fa2 in ReadParamDesc(_IO_FILE*, unsigned short) () from /usr/lib/libtesseract.so.3
#9  0x00007f3485dfba58 in tesseract::Classify::ReadNormProtos(_IO_FILE*, long long) () from /usr/lib/libtesseract.so.3
#10 0x00007f3485ddb9bd in tesseract::Classify::InitAdaptiveClassifier(bool) () from /usr/lib/libtesseract.so.3
#11 0x00007f3485dd40f7 in tesseract::Wordrec::program_editup(char const*, bool, bool) () from /usr/lib/libtesseract.so.3
#12 0x00007f3485d03c29 in tesseract::Tesseract::init_tesseract_internal(char const*, char const*, char const*, tesseract::OcrEngineMode, char**, int, GenericVector<STRING> const*, GenericVector<STRING> const*, bool) () from /usr/lib/libtesseract.so.3
#13 0x00007f3485d0449f in tesseract::Tesseract::init_tesseract(char const*, char const*, char const*, tesseract::OcrEngineMode, char**, int, GenericVector<STRING> const*, GenericVector<STRING> const*, bool) () from /usr/lib/libtesseract.so.3
#14 0x00007f3485cb84bc in tesseract::TessBaseAPI::Init(char const*, char const*, tesseract::OcrEngineMode, char**, int, GenericVector<STRING> const*, GenericVector<STRING> const*, bool) () from /usr/lib/libtesseract.so.3
#15 0x000000000043f7b0 in Config::setDataLocations(int) ()
#16 0x00007f348524b87a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#17 0x00007f34841de7c1 in QComboBox::currentIndexChanged(int) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#18 0x00007f34841de821 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00007f34841deacc in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#20 0x00007f34841ded1f in QComboBox::setCurrentIndex(int) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#21 0x000000000043e5d4 in Config::Config(QWidget*) ()
#22 0x000000000045311d in MainWindow::MainWindow(QStringList const&) ()
#23 0x0000000000433af2 in main ()


Thread 4 (Thread 0x7f3472aeb700 (LWP 3079)):
#0  0x00007f3482c41fdd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f34814e7fe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f34814e830a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f347890b336 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f348150cf05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f348253a184 in start_thread (arg=0x7f3472aeb700) at pthread_create.c:312
#6  0x00007f3482c4f37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111


Thread 3 (Thread 0x7f34722ea700 (LWP 3080)):
#0  0x00007f3482c41fdd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f34814e7fe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f34814e80ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f34814e8129 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f348150cf05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f348253a184 in start_thread (arg=0x7f34722ea700) at pthread_create.c:312
#6  0x00007f3482c4f37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111


Thread 2 (Thread 0x7f34608b0700 (LWP 3083)):
#0  0x00007f3482c46c53 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f3485214171 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007f348513532f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00007f348253a184 in start_thread (arg=0x7f34608b0700) at pthread_create.c:312
#4  0x00007f3482c4f37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111


Thread 1 (Thread 0x7f348657c840 (LWP 3078)):
#0  0x00007f3482c46c53 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f34852622c7 in qt_safe_select(int, fd_set*, fd_set*, fd_set*, timeval const*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007f3485210c52 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00007f348521244a in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007f34851c8652 in QProcess::waitForFinished(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00000000004529ee in MainWindow::signalHandler(int) ()
#6  <signal handler called>
#7  0x00007f3485e5633a in ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const () from /usr/lib/libtesseract.so.3
#8  0x00007f3485de7fa2 in ReadParamDesc(_IO_FILE*, unsigned short) () from /usr/lib/libtesseract.so.3
#9  0x00007f3485dfba58 in tesseract::Classify::ReadNormProtos(_IO_FILE*, long long) () from /usr/lib/libtesseract.so.3
#10 0x00007f3485ddb9bd in tesseract::Classify::InitAdaptiveClassifier(bool) () from /usr/lib/libtesseract.so.3
#11 0x00007f3485dd40f7 in tesseract::Wordrec::program_editup(char const*, bool, bool) () from /usr/lib/libtesseract.so.3
#12 0x00007f3485d03c29 in tesseract::Tesseract::init_tesseract_internal(char const*, char const*, char const*, tesseract::OcrEngineMode, char**, int, GenericVector<STRING> const*, GenericVector<STRING> const*, bool) () from /usr/lib/libtesseract.so.3
#13 0x00007f3485d0449f in tesseract::Tesseract::init_tesseract(char const*, char const*, char const*, tesseract::OcrEngineMode, char**, int, GenericVector<STRING> const*, GenericVector<STRING> const*, bool) () from /usr/lib/libtesseract.so.3
#14 0x00007f3485cb84bc in tesseract::TessBaseAPI::Init(char const*, char const*, tesseract::OcrEngineMode, char**, int, GenericVector<STRING> const*, GenericVector<STRING> const*, bool) () from /usr/lib/libtesseract.so.3
#15 0x000000000043f7b0 in Config::setDataLocations(int) ()
#16 0x00007f348524b87a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#17 0x00007f34841de7c1 in QComboBox::currentIndexChanged(int) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#18 0x00007f34841de821 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00007f34841deacc in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#20 0x00007f34841ded1f in QComboBox::setCurrentIndex(int) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#21 0x000000000043e5d4 in Config::Config(QWidget*) ()
#22 0x000000000045311d in MainWindow::MainWindow(QStringList const&) ()
#23 0x0000000000433af2 in main ()
```

Xubuntu 14.04 x86_64
qImageReader 3.1.99 from the PPA

**Comment by danpla** [comment]
In terminal:
```
Error: Illegal min or max specification!
"Fatal error encountered!" == NULL:Error:Assert failed:in file globaloc.cpp, line 75
```

**Comment by manisandro** [comment]
Argh caused by an oldish version of tesseract which incorrectly deals with locales which have a comma as decimal separator. I'll push a fixed build. Thanks for reporting!

**Comment by manisandro** [comment]
Please test gimagereader - 3.1.99-1~trustyppa2

**Comment by danpla** [comment]
Works now. Thanks!
