### ISSUE TITLE
Crash on merging 5 words in hOCR mode on Qt5

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#250]
Marked 5 words (see below), right-clicked, clicked merge -> crash

`<span class="ocrx_word" id="word_37_39" title="bbox 942 678 966 710; x_wconf 81; x_font Verdana; x_fsize 10" dir="ltr" lang="de_DE">b</span> <span class="ocrx_word" id="word_37_40" title="bbox 1010 668 1012 726; x_wconf 92; x_font Verdana; x_fsize 10" lang="de_DE">|</span> <span class="ocrx_word" id="word_37_41" title="bbox 1063 687 1081 710; x_wconf 93; x_font Verdana; x_fsize 10" dir="ltr" lang="de_DE">c</span> <span class="ocrx_word" id="word_37_42" title="bbox 1162 663 1319 727; x_wconf 42; x_font Verdana; x_fsize 10" dir="ltr" lang="de_DE">fie</span> <span class="ocrx_word" id="word_37_43" title="bbox 1363 669 1365 729; x_wconf 90; x_font Verdana; x_fsize 10" lang="de_DE">|</span>
`

Crash dump:
```
gImageReader 3.2.3 (5c01d6b6b8c69a1daa12719c4144263230fa9668)


#1  0x00007f8511241ce1 in qt_safe_poll(pollfd*, unsigned long, timespec const*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007f8511173c4b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007f851116987b in QProcess::waitForFinished(int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x0000557dc0ab9d8b in MainWindow::signalHandler(int) ()
#5  <signal handler called>
#6  0x00007f85128dbfb8 in QDomElement::text() const () from /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5
#7  0x0000557dc0afa7f7 in HOCRItem::text() const ()
#8  0x0000557dc0af58b0 in HOCRDocument::mergeItems(QModelIndex const&, int, int) ()
#9  0x0000557dc0b0c55f in OutputEditorHOCR::showTreeWidgetContextMenu(QPoint const&) ()
#10 0x0000557dc0b1fe1e in OutputEditorHOCR::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#11 0x00007f851121bc75 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f8511f8d1d5 in QWidget::customContextMenuRequested(QPoint const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007f8511fa79eb in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007f85120479de in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007f8512050a03 in QAbstractScrollArea::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007f85121ba87b in QAbstractItemView::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007f8511f6859c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007f8511f70bce in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007f85111ed178 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007f8511fc2613 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007f8511fc3e22 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007f8511f6859c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007f8511f6fe64 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f85111ed178 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007f85117aa98d in QGuiApplicationPrivate::processContextMenuEvent(QWindowSystemInterfacePrivate::ContextMenuEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007f85117aebd5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007f8511786cab in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007f850556dd50 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#29 0x00007f850ca56f67 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007f850ca571a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007f850ca5722c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007f851124600f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007f85111eb1ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007f85111f4134 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x0000557dc0b1492f in main ()


Thread 10 (Thread 0x7f84d2535700 (LWP 21090)):
#0  0x00007f851027ab26 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f851101057b in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x0000557dc0aad67c in Displayer::scaleThread() ()
#3  0x0000557dc0ab32a7 in void std::__invoke_impl<void, void (Displayer::*&)(), Displayer*&>(std::__invoke_memfun_deref, void (Displayer::*&)(), Displayer*&) ()
#4  0x0000557dc0ab306d in std::__invoke_result<void (Displayer::*&)(), Displayer*&>::type std::__invoke<void (Displayer::*&)(), Displayer*&>(void (Displayer::*&)(), Displayer*&) ()
#5  0x0000557dc0ab2ce6 in void std::_Bind<void (Displayer::*(Displayer*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) ()
#6  0x0000557dc0ab2048 in void std::_Bind<void (Displayer::*(Displayer*))()>::operator()<, void>() ()
#7  0x0000557dc0ab08de in std::_Function_handler<void (), std::_Bind<void (Displayer::*(Displayer*))()> >::_M_invoke(std::_Any_data const&) ()
#8  0x0000557dc0aaf6a4 in std::function<void ()>::operator()() const ()
#9  0x0000557dc0aaf360 in Displayer::ScaleThread::run() ()
#10 0x00007f851100f14d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f8510274519 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#12 0x00007f850ffb6a5f in clone () from /lib/x86_64-linux-gnu/libc.so.6


Thread 9 (Thread 0x7f84e3fff700 (LWP 21088)):
#0  0x00007f850ffaca6d in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f84ca4c9fba in ?? () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#2  0x00007f84ca4c9b61 in avahi_simple_poll_run () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#3  0x00007f84ca4c9d38 in avahi_simple_poll_iterate () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#4  0x00007f84ca4c9f53 in avahi_simple_poll_loop () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#5  0x00007f84ca4ca017 in ?? () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#6  0x00007f8510274519 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007f850ffb6a5f in clone () from /lib/x86_64-linux-gnu/libc.so.6


Thread 8 (Thread 0x7f84d2f70700 (LWP 21081)):
#0  0x00007f851027ab26 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f84e0ff523b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#2  0x00007f84e0ff5157 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#3  0x00007f8510274519 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007f850ffb6a5f in clone () from /lib/x86_64-linux-gnu/libc.so.6


Thread 7 (Thread 0x7f84d3fff700 (LWP 21080)):
#0  0x00007f851027ab26 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f84e0ff523b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#2  0x00007f84e0ff5157 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#3  0x00007f8510274519 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007f850ffb6a5f in clone () from /lib/x86_64-linux-gnu/libc.so.6


Thread 6 (Thread 0x7f84e37fe700 (LWP 21079)):
#0  0x00007f850ffaca6d in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f850ca57119 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f850ca5722c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f851124600f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f85111eb1ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f851100a27a in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f851100f14d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f8510274519 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f850ffb6a5f in clone () from /lib/x86_64-linux-gnu/libc.so.6


Thread 5 (Thread 0x7f84eb7fe700 (LWP 21077)):
#0  0x00007f850ffaca6d in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f84f0122baf in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#2  0x00007f8510274519 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f850ffb6a5f in clone () from /lib/x86_64-linux-gnu/libc.so.6


Thread 4 (Thread 0x7f84ebfff700 (LWP 21076)):
#0  0x00007f851027ab26 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f851101057b in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x0000557dc0b1a200 in Utils::AsyncQueue<ScannerSane::Request>::dequeue() ()
#3  0x0000557dc0b14e3c in ScannerSane::run() ()
#4  0x0000557dc0b20079 in ScannerSane::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#5  0x00007f851121bc75 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f8511008fd7 in QThread::started(QThread::QPrivateSignal) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f851100f134 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f8510274519 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007f850ffb6a5f in clone () from /lib/x86_64-linux-gnu/libc.so.6


Thread 3 (Thread 0x7f84f4301700 (LWP 21075)):
#0  0x00007f850ffaca6d in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f850ca57119 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f850ca5722c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f851124600f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f85111eb1ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f851100a27a in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f8512b19e45 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007f851100f14d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f8510274519 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007f850ffb6a5f in clone () from /lib/x86_64-linux-gnu/libc.so.6


Thread 2 (Thread 0x7f8502be1700 (LWP 21074)):
#0  0x00007f850ffaca6d in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8506edd150 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f8506edeee9 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f850550b029 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f851100f14d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f8510274519 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f850ffb6a5f in clone () from /lib/x86_64-linux-gnu/libc.so.6


Thread 1 (Thread 0x7f8514a67540 (LWP 21073)):
#0  0x00007f850ffacb5b in ppoll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8511241ce1 in qt_safe_poll(pollfd*, unsigned long, timespec const*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007f8511173c4b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007f851116987b in QProcess::waitForFinished(int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x0000557dc0ab9d8b in MainWindow::signalHandler(int) ()
#5  <signal handler called>
#6  0x00007f85128dbfb8 in QDomElement::text() const () from /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5
#7  0x0000557dc0afa7f7 in HOCRItem::text() const ()
#8  0x0000557dc0af58b0 in HOCRDocument::mergeItems(QModelIndex const&, int, int) ()
#9  0x0000557dc0b0c55f in OutputEditorHOCR::showTreeWidgetContextMenu(QPoint const&) ()
#10 0x0000557dc0b1fe1e in OutputEditorHOCR::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#11 0x00007f851121bc75 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f8511f8d1d5 in QWidget::customContextMenuRequested(QPoint const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007f8511fa79eb in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007f85120479de in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007f8512050a03 in QAbstractScrollArea::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007f85121ba87b in QAbstractItemView::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007f8511f6859c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007f8511f70bce in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007f85111ed178 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007f8511fc2613 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007f8511fc3e22 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007f8511f6859c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007f8511f6fe64 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f85111ed178 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007f85117aa98d in QGuiApplicationPrivate::processContextMenuEvent(QWindowSystemInterfacePrivate::ContextMenuEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007f85117aebd5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007f8511786cab in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007f850556dd50 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#29 0x00007f850ca56f67 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007f850ca571a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007f850ca5722c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007f851124600f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007f85111eb1ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007f85111f4134 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x0000557dc0b1492f in main ()
```

**Comment by manisandro** [comment]
Please re-test with the latest git master, and if you can still trigger a crash, send me the full hOCR document (or at least the complete page) if possible. Thanks

**Comment by SantosSi** [comment]
Yes, it still crashes.
"Luckily" I already sent you the html and pdf files. The nodes above are in ...Kap5Anhang-manis1.html on page 37, seventh text block, first paragraph, second textline.

**Comment by manisandro** [comment]
Could you send the files again? Can't find them anymore...

**Comment by manisandro** [comment]
Any chance you could send me the source files? I'd like to investigate this.

**Comment by SantosSi** [comment]
Sorry, for that. The email I immediately 
created was not sent due to size without 
my notice. Resent with a tar.bz archive.

**Comment by manisandro** [comment]
Thanks, could reproduce, need to investigate further to understand what's going on...
