### ISSUE TITLE
Qt: crash on overwriting hOCR + file set to 0 bytes

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#375]
V 3.3.0 Qt, commit 17a392
Saved a freshly OCRed hOCR file, closed gIR. Restarted gIR, loaded the hOCR file, edited contents. In the Output area clicked the save button, selected the file openend before and confirmed overwriting: gIR crashes with no error message and destroys the hOCR content by leaving the file at 0 bytes.
This is reproducible, happens on a common and often used task and destroys previous work results!

**Comment by manisandro** [comment]
Can you post a stack trace?

**Comment by SantosSi** [comment]
./gimagereader-qt5 
Failed to open /usr/local/share/xml/iso-codes/iso_639.xml for reading
Failed to open /usr/local/share/xml/iso-codes/iso_3166.xml for reading
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3565, resource id: 25175174, major code: 40 (TranslateCoords), minor code: 0
QGraphicsScene::removeItem: cannot remove 0-item
kf5.kio.widgets: No node found for item that was just removed: QUrl("file:///home/test/0001.tif")
!strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 203
!strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 203
Speicherzugriffsfehler

**Comment by manisandro** [comment]
Please run in gdb:

    gdb ./gimagereader-qt5
    run
    # Make it crash
    thread apply all bt

and then post back the stacktrace here.

**Comment by SantosSi** [comment]
Thread 9 (Thread 0x7fffb99d3700 (LWP 5463)):
#0  0x00007ffff5427e6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff58624fb in QWaitCondition::wait(QMutex*, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00005555555ca916 in Displayer::scaleThread() ()
    at source/gImageReader/qt/src/Displayer.cc:530
#3  0x00007ffff5861d47 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff5421f2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007ffff5354edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 8 (Thread 0x7fffc0854700 (LWP 5457)):
#0  0x00007ffff534a739 in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffc9253f6a in ?? () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#2  0x00007fffc9253b11 in avahi_simple_poll_run () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#3  0x00007fffc9253ce8 in avahi_simple_poll_iterate () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#4  0x00007fffc9253f03 in avahi_simple_poll_loop () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#5  0x00007fffc9253fc7 in ?? () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#6  0x00007ffff5421f2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007ffff5354edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 7 (Thread 0x7fffd9acd700 (LWP 5456)):
#0  0x00007ffff5427e6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fffdaff090b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#2  0x00007fffdaff0637 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#3  0x00007ffff5421f2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007ffff5354edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7fffda646700 (LWP 5455)):
#0  0x00007ffff5427e6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fffdaff090b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#2  0x00007fffdaff0637 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#3  0x00007ffff5421f2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007ffff5354edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7fffe1b40700 (LWP 5454)):
#0  0x00007ffff534a739 in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffe1b50fbf in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#2  0x00007ffff5421f2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007ffff5354edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7fffe27b4700 (LWP 5453)):
#0  0x00007ffff5427e6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff58624fb in QWaitCondition::wait(QMutex*, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x000055555563afea in Utils::AsyncQueue<ScannerSane::Request>::dequeue (this=0x555555cd3238)
    at source/gImageReader/qt/src/scanner/ScannerSane.cc:98
#3  ScannerSane::run() () at source/gImageReader/qt/src/scanner/ScannerSane.cc:78
#4  0x00007ffff5a337bb in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff5857117 in QThread::started(QThread::QPrivateSignal) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff5861d30 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff5421f2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007ffff5354edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

---Type <return> to continue, or q <return> to quit---
Thread 3 (Thread 0x7fffe413a700 (LWP 5452)):
#0  0x00007ffff534a739 in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff28e0e46 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff28e0f6c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff5a5c223 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff5a0924b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff5858176 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff692a545 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007ffff5861d47 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff5421f2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007ffff5354edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7fffecaa2700 (LWP 5451)):
#0  0x00007ffff534a739 in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffef448cf7 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fffef44a90a in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fffeddbe159 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007ffff5861d47 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff5421f2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff5354edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7fffeee108c0 (LWP 5447)):
#0  0x00007ffff7c1a037 in ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const ()
   from /usr/lib/x86_64-linux-gnu/libtesseract.so.4
#1  0x00007ffff7a4ee5e in tesseract::TessBaseAPI::TessBaseAPI() ()
   from /usr/lib/x86_64-linux-gnu/libtesseract.so.4
#2  0x000055555562c4ba in OutputEditorHOCR::save(QString const&) ()
    at source/gImageReader/qt/src/hocr/OutputEditorHOCR.cc:845
#3  0x000055555563d1e8 in OutputEditorHOCR::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:693
#4  0x00007ffff5a337bb in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff635cef2 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff635f500 in QAction::activate(QAction::ActionEvent) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff644ad1d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff644af55 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff6534caa in QToolButton::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff63a17d8 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff6534d53 in QToolButton::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff63634a1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff636ad28 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff5a0a579 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff636a029 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff63bc304 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff63bee8e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff63634a1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#19 0x00007ffff636aae0 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff5a0a579 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff5da953b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#22 0x00007ffff5dab435 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#23 0x00007ffff5d85b6b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)
    () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#24 0x00007fffede4fe5b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#25 0x00007ffff5a0924b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff5a113c2 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00005555555af3e2 in main () at source/gImageReader/qt/src/main.cc:94
#28 0x00007ffff527fb17 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#29 0x00005555555af5fa in _start () at /usr/include/c++/8/bits/std_function.h:257

**Comment by manisandro** [comment]
Please try with 46390fee9a01ea7c4d85cd0757a6a258c8ebe600

**Comment by SantosSi** [comment]
Working OK. Thanks for quickly resolving.

**Comment by manisandro** [comment]
I take you are using tesseract 4.x?

**Comment by SantosSi** [comment]
Yes: 4.0.0-beta-4.50

**Comment by manisandro** [comment]
Hm ok so they changed behaviour...
