### ISSUE TITLE
Ubuntu Mate 18.04: Crash when opening "Manage Languages" menu on GTK build

### ISSUE THREAD

**Issue by CTXz** [manisandro/gImageReader#389]
Whilst attempting to access the "Manage Languages" menu on the latest GTK build from source (altough the same issue applies for the deb packages), gImageReader crashes:

```
(gimagereader-gtk:4247): glibmm-ERROR **: 12:09:58.093: 
unhandled exception (type std::exception) in signal handler:
what: basic_string::_M_construct null not valid

Trace/breakpoint trap (core dumped)
```

I'm currently using Ubuntu Mate 18.04

**Comment by manisandro** [comment]
Can you post a full stacktrace? I.e. run the application within gdb?

**Comment by CTXz** [comment]
```
(gdb) r
Starting program: /home/ctxz/dev/gImageReader/build/gimagereader-gtk 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe2658700 (LWP 3885)]
[New Thread 0x7fffe1e57700 (LWP 3886)]
[New Thread 0x7fffe1656700 (LWP 3887)]
[New Thread 0x7fffe09e4700 (LWP 3888)]
[New Thread 0x7fffd3df9700 (LWP 3889)]
[New Thread 0x7fffd33e3700 (LWP 3890)]
[New Thread 0x7fffc6cc3700 (LWP 3891)]
[New Thread 0x7fffc4c29700 (LWP 3894)]
[Thread 0x7fffc6cc3700 (LWP 3891) exited]
[New Thread 0x7fffc6cc3700 (LWP 3897)]
[New Thread 0x7fffa7bb6700 (LWP 3899)]
[Thread 0x7fffe09e4700 (LWP 3888) exited]
[Thread 0x7fffc6cc3700 (LWP 3897) exited]
[New Thread 0x7fffc6cc3700 (LWP 3901)]
[New Thread 0x7fffe09e4700 (LWP 3902)]

(gimagereader-gtk:3881): glibmm-ERROR **: 17:29:54.341: 
unhandled exception (type std::exception) in signal handler:
what: basic_string::_M_construct null not valid


Thread 1 "gimagereader-gt" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff46f1cc1 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) backtrace 
#0  0x00007ffff46f1cc1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff46f2cfc in g_log_default_handler () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff46f2f8d in g_logv () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff46f30ff in g_log () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff6233e2f in Glib::exception_handlers_invoke() () at /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#5  0x00007ffff623a557 in Glib::SignalProxyNormal::slot0_void_callback(_GObject*, void*) () at /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#6  0x00007ffff49c610d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff49d8b61 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff49e1685 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff49e209f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff5c51fa6 in gtk_widget_activate () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff5b248c6 in gtk_menu_shell_activate_item () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff5b24b42 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff727d717 in Gtk::Widget::on_button_release_event(_GdkEventButton*) () at /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#14 0x00007ffff727f834 in Gtk::Widget_Class::button_release_event_callback(_GtkWidget*, _GdkEventButton*) () at /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#15 0x00007ffff5b08257 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff49c6346 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff49e133d in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff49e209f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff5c4fb04 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff5b051ce in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff5b072a8 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff5618765 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#23 0x00007ffff5648f82 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#24 0x00007ffff46ec287 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff46ec4c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff46ec54c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff50d7ddd in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#28 0x00005555557f8f66 in main(int, char**) (argc=1, argv=0x7fffffffdf98) at /home/ctxz/dev/gImageReader/gtk/src/main.cc:124
```

**Comment by webbby** [comment]
I have the same crash as well

**Comment by Dombot3** [comment]
I have the same issue. Is there a workaround?

**Comment by manisandro** [comment]
Should be fixed by https://github.com/manisandro/gImageReader/commit/7a98248b0ce16c07b50587add3f9cef2d6883726
